### ISSUE TITLE
SecureJS source code

### ISSUE THREAD

**Issue by JoaoPere** [AsierRF/SecureJS#1]
Hello. Read your thesis recently and found it interesting. However, when linking to the GitHub project mentioned in the document it is no longer available. Any chance I can take a look at it out of curiosity? I'm currently doing my own thesis with a similar concept even though there is no Trusted Execution within enclaves but it was one of the core areas that got my attention during research.

**Comment by AsierRF** [comment]
Dear JoaoPere,

Sorry for the late response and thanks for reading my thesis.

This is a task that I have pending, I should have done it right after I finished my thesis. However, my calendar was quite full at that moment.

Since you have interest in my work, I will try to work on the repository during this week. I can't promise it will be ready during this week but I will try my best.

Kind regards,
Asier Rivera.

**Comment by AsierRF** [comment]
Dear JoaoPere,

I just added the code. I hope you still find it useful. 

Kind regards,
Asier Rivera.
